djcrm/urls.py
from os import name # for naming convention for urls
from django.contrib import admin
from django.urls import path,include

from django.contrib.auth.views import (
  LoginView, 
  LogoutView,
  PasswordResetView,
  PasswordResetDoneView,
  PasswordResetConfirmView,
  PasswordResetCompleteView
  )
from leads.views import LandingPageView, SignUpView ,user_logout


from django.conf import settings
from django.conf.urls.static import static






urlpatterns = [
    path('admin/', admin.site.urls),
    path('',LandingPageView.as_view(),name='landing'),
    path('signup/', SignUpView.as_view(), name='sign'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', user_logout, name='logout'),


    #password reset urls 
    path('password-reset/', PasswordResetView.as_view(), name='password-reset'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('Password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

   
    path('leads/',include('leads.urls',namespace='leads')),    # urls file in the leads app
    path('agents/',include('agents.urls',namespace='agents')), # urls file in the agents app
]

if settings.DEBUG :
  urlpatterns+= static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from .views import (
  LandingPageView,
  LeadListView, 
  LeadDetailView,
  LeadCreateView,
  LeadUpdateView,
  LeadDeleteView,
  AssignAgentView,
  CategoryView,
  CategoryDetailView,
  LeadCategoryUpdateView,
)

app_name = "leads"

urlpatterns = [

  path('',LeadListView.as_view(),name='lead-list'),
  path('<int:pk>/',LeadDetailView.as_view(),name='lead-detail'),
  path('create/',LeadCreateView.as_view(),name='lead-create'),
  path('<int:pk>/update/',LeadUpdateView.as_view(),name='lead-update'),
  path('<int:pk>/delete/', LeadDeleteView.as_view(), name='lead-delete'),
  path('<int:pk>/assign-agent/',AssignAgentView.as_view(),name='assign-agent'),

   path('category/', CategoryView.as_view(), name='category-view'),
   path('category/<int:pk>/',CategoryDetailView.as_view(),name='category-detail-view'),
   path('<int:pk>/category/',LeadCategoryUpdateView.as_view(),name='category-update-view'),
 
]

leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save #import the signal 

class User(AbstractUser):
  # let's check if the user is a Organizer or an Agent videoTimeline : 05:37
  is_organizer=models.BooleanField(default=True)
  is_agent = models.BooleanField(default=False)

# Every User has a userprofile or known as userprofile
class UserProfile(models.Model):
  user  = models.OneToOneField(User,on_delete=models.CASCADE)

  def __str__(self) -> str:
    return self.user.username

class Lead(models.Model):
  first_name = models.CharField(max_length=20)
  last_name = models.CharField(max_length=20)
  age = models.IntegerField(default=0)
  # agent = models.ForeignKey("Agent",on_delete=models.CASCADE)
  # here going to change the above line to as follows for the filtering purpose
  organization = models.ForeignKey(UserProfile,on_delete=models.CASCADE)
  agent = models.ForeignKey("Agent",null=True,blank=True,on_delete=models.SET_NULL)
  category = models.ForeignKey("Category",null=True,blank=True,on_delete=models.SET_NULL,related_name="leads") #the related name helps to get Lead details within the category(revese relationship)
  description = models.TextField()
  date_added = models.DateTimeField(auto_now_add=True)
  phone_number = models.CharField(max_length=14)
  email = models.EmailField()

  def __str__(self):
    return f"{self.first_name} {self.last_name}"
  
class Agent(models.Model):
  user = models.OneToOneField(User,on_delete=models.CASCADE) 
  organization = models.ForeignKey(UserProfile,on_delete=models.CASCADE)


  def __str__(self):
    return self.user.username
  


class Category(models.Model):
  name = models.CharField(max_length=30)
  organization = models.ForeignKey(UserProfile,on_delete=models.CASCADE)

  def __str__(self):
    return self.name
  


















#we use post save to Automatically create UserProfile for each User when a User is Created
def post_user_created(sender,instance,created, **kwargs): #this method will be called when the post_save signal implements
  if(created):
    UserProfile.objects.create(user = instance)  # this will create a UserProfile for the newly created user instance

post_save.connect(post_user_created,sender=User) #implements when a New User is created or saved some changes into a User in the above user Model

leads/forms.py
from django import forms
from .models import Lead,Agent

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit,Field,Layout

from django.contrib.auth.forms import UserCreationForm,UsernameField
from django.contrib.auth import get_user_model

User = get_user_model()

class CustomUserCreationForm(UserCreationForm):
  class Meta:
    model = User
    fields=("username",)
    field_classes={'username':UsernameField}


class LeadModelForm(forms.ModelForm):
  class Meta:
    model = Lead
    fields=(
      'first_name',
      'last_name',
      'age',
      'agent',
      'description',
      'phone_number',
      'email',
    )
  def __init__(self,*args,**kwargs):
    super().__init__(*args,**kwargs)
    self.helper = FormHelper()
    # Apply class to all labels
    self.fields['first_name'].widget.attrs.update({
      'class': 'appearance-none rounded-md relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-purple-500 focus:border-purple-500 focus:z-10 sm:text-sm border-l-4 border-l-purple-600',
      'placeholder': 'First Name',
      'id':'firstName',
    
    })
  
    self.fields['last_name'].widget.attrs.update({
      'class': 'appearance-none rounded-md relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-purple-500 focus:border-purple-500 focus:z-10 sm:text-sm border-l-4 border-l-purple-600',
      'placeholder': 'Last Name',
    })
    
    self.fields['age'].widget.attrs.update({
      'class': 'appearance-none rounded-md relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-purple-500 focus:border-purple-500 focus:z-10 sm:text-sm border-l-4 border-l-purple-600',
      'placeholder': 'Last Name',
    })
    self.fields['agent'].widget.attrs.update({
      'class': 'appearance-none rounded-md relative block w-full px-3 py-2 border border-gray-900 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-purple-500 focus:border-purple-500 focus:z-10 sm:text-sm border-l-4 border-l-purple-600',
      
    })

    self.helper.label_class = "block text-sm font-medium text-purple-500"
     # Apply class to all labels
   
   


class LeadForm(forms.Form):
  first_name = forms.CharField()
  last_name  = forms.CharField()
  age = forms.IntegerField(min_value=0)


# this form is used to select an agent for a lead who haven't been assigned an agent
class AssignAgentForm(forms.Form):
  agent = forms.ModelChoiceField(     # the field is a option field where all the agents belong to the lead organization will be appeared 
    queryset=Agent.objects.none()     # for now keep it as it is untill we assign the correct queryset from below
  )
 
  def __init__(self, *args, **kwargs):  
      
      request = kwargs.pop("request")   # get the request user. which is the added kwargs within the view 
      agents = Agent.objects.filter(organization = request.user.userprofile)  # here we get those agents belongs to the same organization that the lead belongs 
      super(AssignAgentForm, self).__init__(*args, **kwargs) 
      self.fields["agent"].queryset = agents  # assign the query set here and now it will be this instead of none as above 



class LeadCategoryUpdateForm(forms.ModelForm):
  class Meta:
    model = Lead
    fields = (
      'category',
    )

leads/views.py
from typing import Any
from django.db.models.query import QuerySet     # Import to handle database Query Sets            
from django.forms import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render, reverse, redirect
from django.views import generic               # This includes all the CRUD Operations 
from .models import Lead,Category #This is the Lead Model or Table we created in Models.py we use this here to interact with the tabel data
from .forms import LeadModelForm, CustomUserCreationForm,AssignAgentForm,LeadCategoryUpdateForm  #this includes the Custom Forms or Overridden forms crated within the Forms.py file

from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin # This Method will check if the Requesting User is Logged in or Not
from agents.mixins import OrganizerAndLoginRequiredMixin  # This is the My custom created LoginRequired Mixin created within the Agents App 
# Create your views here.

@login_required
def user_logout(request):
   """Logs out the user and renders the logged_out template."""
   logout(request)
   return render(request,"registration/logged_out.html")











"""
**SignUpView**

This view handles user registration using the custom `CustomUserCreationForm`.
"""

class SignUpView(generic.CreateView):
  template_name ="registration/signup.html"  #this is the Template this class going to Use 
  form_class = CustomUserCreationForm

  def get_success_url(self):
    return reverse('login')


"""
**LandingPageView**

This view simply renders the `landing-page.html` template.
"""
class LandingPageView(generic.TemplateView):
  template_name = "landing-page.html"
  context_object_name = 'leads'

  def get_queryset(self):
    queryset = Lead.objects.all()
    return queryset
  

"""
**LeadListView**

This view displays a list of leads for the currently logged-in user,
filtering based on their role (organizer or agent).

- LoginRequiredMixin ensures only authenticated users can access this view.
"""


class LeadListView(LoginRequiredMixin,generic.ListView):
  template_name = "leads/leads-list.html"
  context_object_name = "leads"

  def get_queryset(self):
    user = self.request.user  #Assign the Current user
    if user.is_organizer:     # Check if the user is an Organizer True
      queryset = Lead.objects.filter(
        # get all the leads where there organization equal to the organization of the current User and agent field is not null 
        organization = user.userprofile, 
        agent__isnull =False  # this will get leads who are assigned to an Agent
    
      )
    else: # else meaning now  the current user is an Agent 
      queryset = Lead.objects.filter(
        #
        organization = user.agent.organization,
        agent__isnull =False
      )
      queryset = queryset.filter(
        # an agent is also a user
        # so this query will get leads who have assigned to him
        agent__user = user # this is like saying get every leads who have assigned to this agent 
      )
    return queryset
  

  # The following is the way to classify the leads with agents and with no-agents 
  # The method is used to overide the context and add aditional things to the context  
  def get_context_data(self, **kwargs):
    context = super(LeadListView, self).get_context_data(**kwargs)
    user = self.request.user
    if user.is_organizer:
      queryset = Lead.objects.filter(
        organization = user.userprofile, 
        agent__isnull = True
      )
      context.update({
        "unassigned_leads" : queryset
      })
    return context
  




class LeadDetailView(LoginRequiredMixin,generic.DetailView):
  template_name = "leads/lead-detail.html"
  context_object_name ="lead"

  def get_queryset(self):
    user = self.request.user
    if user.is_organizer:
      queryset = Lead.objects.filter(organization = user.userprofile)
    else:
      queryset = Lead.objects.filter(
        organization = user.agent.organization, #give the leads who are in the same organization as the agent
        agent__user = user
      )
    return queryset

class LeadCreateView(OrganizerAndLoginRequiredMixin,generic.CreateView):

  template_name="leads/lead-create.html"
  form_class = LeadModelForm

  def get_success_url(self):
    return reverse('leads:lead-list')
  
  def form_valid(self,form):
    lead = form.save(commit=False)
    lead.organization = self.request.user.userprofile
    lead.save()

    return super(LeadCreateView,self).form_valid(form)


class LeadUpdateView(OrganizerAndLoginRequiredMixin,generic.UpdateView):
  template_name="leads/lead-update.html"
  form_class = LeadModelForm
  
  def get_queryset(self):
    queryset = Lead.objects.filter(organization = self.request.user.userprofile)
    return queryset

  def get_success_url(self):
    return reverse("leads:lead-list")
  
class LeadDeleteView(OrganizerAndLoginRequiredMixin,generic.DeleteView):
  template_name = "leads/lead-delete.html"
 
  def get_success_url(self):
    return reverse("leads:lead-list")
  
  def get_queryset(self):
    queryset = Lead.objects.filter(organization = self.request.user.userprofile)
    return queryset

#This class View is used to assign an agent for leads who are in the Unassigned Agents part
class AssignAgentView(OrganizerAndLoginRequiredMixin,generic.FormView):
  template_name = "leads/assign-agent.html"
  form_class = AssignAgentForm

  #use this method to add additional kwags by using the update func
  def get_form_kwargs(self,**kwags) -> dict[str, Any]:
    kwags =  super(AssignAgentView,self).get_form_kwargs(**kwags)
    kwags.update({
      "request":self.request
    })
    return kwags

  def form_valid(self, form):
    agent = form.cleaned_data["agent"] # get the agent that the user selected in the form
    lead = Lead.objects.get(id = self.kwargs["pk"])  # take the lead object by using the primary key within the url
    lead.agent = agent   # assign the agent to the grabbed lead 
    lead.save()  # save data 
    return super().form_valid(form) 

  def get_success_url(self):
    return reverse('leads:lead-list')
  
class CategoryView(LoginRequiredMixin,generic.ListView):
  template_name = 'leads/category-view.html'
  context_object_name = 'categoryList'

  def get_context_data(self, **kwargs):
    context = super(CategoryView,self).get_context_data(**kwargs)
    user = self.request.user
    if user.is_organizer :
      queryset = Lead.objects.filter(
        organization = user.userprofile
      )
    else:
      queryset = Lead.objects.filter(
        organization = user.agent.organization
      )
    
    unAssignedLeadCount=queryset.filter(category__isnull = True).count()

    context.update({
        "unAssignedLeadCount":unAssignedLeadCount
      
    })
    return context
    

  def get_queryset(self):
    user = self.request.user
    if user.is_organizer :
      queryset = Category.objects.filter(
        organization = user.userprofile
      )
    else:
      queryset = Category.objects.filter(
        organization = user.agent.userprofile
      )
    return queryset
  

class CategoryDetailView(LoginRequiredMixin,generic.DetailView):
  template_name = "leads/category-detail-view.html"
  context_object_name ='category'


  def get_context_data(self, **kwargs):
    context = super(CategoryDetailView,self).get_context_data(**kwargs)
    # qs = Lead.objects.filter(category = self.get_object())  we use the following line instead of this because it do the same thing 
    leads = self.get_object().leads.all()
    

    context.update({
        "leads":leads
      
    })
    return context


  
  def get_queryset(self):
    user = self.request.user
    if user.is_organizer :
      queryset = Category.objects.filter(
        organization = user.userprofile
      )
    else:
      queryset = Category.objects.filter(
        organization = user.agent.userprofile
      )
    return queryset
  
class LeadCategoryUpdateView(LoginRequiredMixin,generic.UpdateView):
  template_name = 'leads/category-update-view.html'
  form_class = LeadCategoryUpdateForm

  def get_queryset(self):
    user = self.request.user
    if user.is_organizer :
      queryset = Lead.objects.filter(
        organization = user.userprofile
      )
    else:
      queryset = Lead.objects.filter(
        organization = user.agent.userprofile
      )
    return queryset
  
  def get_success_url(self) -> str:
    return reverse('leads:lead-detail',kwargs={"pk":self.get_object().id})

leads/templates/leads/assign-agent.html
{% extends 'base.html' %}


{% block content %}

  <h1> Select and Agent</h1>
  <hr>
  
  <form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit"> Set the Agent</button>
  </form>

{% endblock content %}
  

leads/templates/leads/category-update-view.html
{% extends 'base.html' %}

{% load tailwind_filters %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block title %} Add a Lead {% endblock title %} 


{% block content %}


<div class="min-h-screen bg-white flex flex-col justify-center py-12 sm:px-6 lg:px-8">
  <div class="sm:mx-auto sm:w-full sm:max-w-md">
  </div>
  <h2 class="text-sm title-font text-gray-500 tracking-widest">
    Lead Details
  </h2>
  <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
    {{lead.first_name}} {{lead.last_name}}
  </h1>
     
  <div class="bg-white w-[70vw] h-[80vh] mx-auto pt-0 pb-20 px-0 shadow sm:rounded-lg sm:px-0">
      <div class="flex flex-row gap-x-8 justify-center mb-4">
        <a href="{% url 'leads:lead-detail' lead.pk %}"  class=" border-b-2 border-gray-300 py-2 text-lg px-1">Overview</a>
        <a href="{% url 'leads:lead-update' lead.pk %}"  class=" border-b-2 border-gray-300 py-2 text-lg px-1" >  update </a>
        <a href="{% url 'leads:category-update-view' lead.pk %}" class=" text-purple-500 border-b-4 border-purple-500 py-2 text-lg px-1"> Category</a>
      </div>

      <div class="px-40">
        
          <form class="space-y-6" action="#" method="POST">
            {% csrf_token %}
            
              <div class="my-4">
                <label for="{{form.category.id_for_label}}" class="block text-sm font-medium text-gray-700">
                  category
                </label>
                <div class="mt-1">
                  {{form.category|add_class:"border-l-4 border-purple-500 h-12 appearance-none rounded-md relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900  focus:ring-purple-500 focus:border-purple-500 focus:z-10 sm:text-sm"|attr:"placeholder:Description"}}
                </div>
              </div>
              <button type="submit"
                class="group relative w-full flex justify-center mt-10 py-3 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-purple-600 hover:bg-purple-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500">

                Update The Category
              </button>
            </div>
          </form>
          <div class=" relative text-sm top-6 ">
            <a href="{% url 'leads:lead-list' %}"
            class="font-medium text-purple-700 hover:text-purple-500">
                Go back to Leads
            </a>
          </div>
                 
      </div>
  </div>
</div>



  




<script src="https://cdn.tailwindcss.com"></script>

{% endblock content %}

leads/templates/leads/lead-delete.html
{% extends "base.html" %}


{% block title %}

{% endblock title %}


{% block content %}

<form action="" method="post">
  {% csrf_token %}
  <div class=" container h-56 flex flex-col items-center justify-center  bg-white
  mx-auto mt-36
  w-2/4 rounded-xl shadow-2xl shadow-black shadow 
  ">
    <span class=" text-[20px] ">Are You Sure You want to Delete The Lead ?</span>
    <div class="flex flex-row gap-3">
    <a class=" ml-3 mt-3 bg-gray-100 text-red-500 font-semibold border-0 py-2 px-3 focus:outline-none hover:bg-red-400 hover:text-white rounded" href="{% url 'leads:lead-list'  %}" >No, Don't Delete</a>
    <input class=" ml-3 mt-3 text-white bg-red-500 border-0 py-2 px-8 focus:outline-none hover:bg-red-600 rounded" type="submit" value="Yes, Delete"/>
    </div>
  </div>
  
</form>
{% endblock content %}

leads/templates/leads/leads-list.html
{% extends 'base.html' %}
  
{% block title %} HomePage {% endblock title %}  
{% load static %}



{% block content %}

{% include 'navbar.html' %}
<section class="text-gray-600 body-font">
    <div class="flex justify-between pt-5 px-5">
        <h1></h1>

 
        {% if request.user.is_organizer %}
   
        <div class=" flex flex-row items-center  gap-x-1"> 
            <div class=""><span class="   font-semibold hover:text-purple-600 text-purple-400"><a href="{% url 'leads:lead-create' %}">New Lead</a></span ></div><br>
            <div class=""><span class=" hover:text-purple-600 border-l-[3px] pl-1 border-purple-600 font-semibold text-purple-400"><a href="{% url 'leads:category-view' %}">view category</a></span ></div><br>
        
        </div>
        {% endif %}
</div>
<div class="container px-5 py-6 mx-auto flex flex-wrap">
  <h1 class=" py-2 text-3xl ">Leads</h1>
  <table class="min-w-full divide-y divide-purple-200 overflow-x-auto">
    <thead class="bg-purple-700">
        <tr>
            <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-gray-50 uppercase tracking-wider">
               Name
            </th>
            <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-gray-50 uppercase tracking-wider">
                age
            </th>
            <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-gray-50 uppercase tracking-wider">
                Category
            </th>
            <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-gray-50 uppercase tracking-wider">
                agent
            </th>
            <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-gray-50 uppercase tracking-wider">
                Email
            </th>
            <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-gray-50 uppercase tracking-wider">
                Actions
            </th>
        </tr>
    </thead>
    <tbody class="bg-white divide-y divide-gray-200">
      {% for lead in leads %}
      <tr>
        <td class="px-6 py-4 whitespace-nowrap">
            <div class="flex items-center">
                <div class="flex-shrink-0 h-10 w-10">
                    <img class="h-10 w-10 rounded-full" src="https://i.pravatar.cc/150?img=1" alt="">
                </div>
                <div class="ml-4">
                    <div class="text-sm font-medium text-gray-900">
                        {{lead.first_name}} {{lead.last_name}}
                    </div>
                    
                </div>
            </div>
        </td>
        <td class="px-6 py-4 whitespace-nowrap ">
            <div class="text-sm text-gray-900 text-center  ">{{lead.age}}</div>
            
        </td>
        <td class="px-6 py-4 whitespace-nowrap">
          {% if lead.category|lower == "converted" %}
            <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
              {{lead.category}}
          {% elif lead.category|lower == 'unconverted' %}
          <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-yellow-100 text-yellow-800">
            {{lead.category}}
          
          {% elif lead.category|lower == 'contacted' %}
            <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-blue-100 text-blue-800">
              {{lead.category}}

           {% else %}
           <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-100 text-red-800">
            {{lead.category}}
             
              
          {% endif %}
                
            </span>
        </td>
        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
            {{lead.agent}}
        </td>
        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
            
            {% if lead.email %}
            {{lead.email}}
            {% else %}
            <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-100 text-red-800">
                none</span>
            {% endif %}
                
            
        </td>
        <td class="px-6 py-4 whitespace-nowrap  text-sm font-medium">
            <a href="{% url 'leads:lead-update' lead.pk %}" class="text-indigo-600 hover:text-indigo-900">Edit</a>
            <a href="{% url 'leads:lead-delete' lead.pk %}" class="ml-2 text-red-600 hover:text-red-900">Delete</a>
        </td>
    </tr>
      {% endfor %}
      




        <!-- More rows... -->

    </tbody>
</table>

    <div class="flex justify-between pt-5 px-0 w-full">
      {% if unassigned_leads.exists %}
       
    </div>
</div>
<div class="container px-5 py-6 mx-auto flex flex-wrap">
    <h1 class=" py-2 text-3xl ">Unassigned Leads</h1>
   
    <table class="min-w-full divide-y divide-purple-300 overflow-x-auto">
      <thead class="bg-red-400">
          <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-gray-50 uppercase tracking-wider">
                 Name
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-gray-50 uppercase tracking-wider">
                  age
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-gray-50 uppercase tracking-wider">
                  Category
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-gray-50 uppercase tracking-wider">
                  agent
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-gray-50 uppercase tracking-wider">
                  Email
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-gray-50 uppercase tracking-wider">
                  Actions
              </th>
          </tr>
      </thead>
      <tbody class="bg-white divide-y divide-gray-200">
        {% for lead in unassigned_leads %}
        <tr>
          <td class="px-6 py-4 whitespace-nowrap">
              <div class="flex items-center">
                  <div class="flex-shrink-0 h-10 w-10">
                      <img class="h-10 w-10 rounded-full" src="https://i.pravatar.cc/150?img=1" alt="">
                  </div>
                  <div class="ml-4">
                      <div class="text-sm font-medium text-gray-900">
                          {{lead.first_name}} {{lead.last_name}}
                      </div>
                      
                  </div>
              </div>
          </td>
          <td class="px-6 py-4 whitespace-nowrap ">
              <div class="text-sm text-gray-900 text-end ">{{lead.age}}</div>
              
          </td>
          <td class="px-6 py-4 whitespace-nowrap">
            {% if lead.category|lower == "converted" %}
              <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                {{lead.category}}
            {% elif lead.category|lower == 'unconverted' %}
            <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-yellow-100 text-yellow-800">
              {{lead.category}}
            
            {% elif lead.category|lower == 'contacted' %}
              <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-blue-100 text-blue-800">
                {{lead.category}}
  
             {% else %}
             <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-red-100 text-red-800">
              {{lead.category}}
               
                
            {% endif %}
                  
              </span>
          </td>
          <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
              {{lead.agent}}
          </td>
          <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
              jane.cooper@example.com
          </td>
          <td class="px-6 py-4 whitespace-nowrap  text-sm font-medium">
              <a href="{% url 'leads:lead-update' lead.pk %}" class="text-indigo-600 hover:text-indigo-900">Edit</a>
              <a href="{% url 'leads:lead-delete' lead.pk %}" class="ml-2 text-red-600 hover:text-red-900">Delete</a>
          </td>
      </tr>
        {% endfor %}
      
    {% endif %}

  </div>
 </div>
</div>

</section>




  
  
{% endblock content %}