agents/urls.py
from django.urls import path 
from .views import AgentListView,AgentCreateView,AgentDetailView,AgentUpdateView,AgentDeleteView

app_name = 'agents' # name of the app and also this is the name provided as namespace inside the main urls file in djcrm

urlpatterns = [
  path('',AgentListView.as_view(),name='agent-list'),
  path('create/',AgentCreateView.as_view(),name='agent-create'),
  path('<int:pk>/',AgentDetailView.as_view(),name='agent-detail'),
  path('<int:pk>/update/',AgentUpdateView.as_view(),name='agent-update'),
  path('<int:pk>/delete/',AgentDeleteView.as_view(),name='agent-delete'),
]

djcrm/urls.py
from os import name # for naming convention for urls
from django.contrib import admin
from django.urls import path,include

from django.contrib.auth.views import (
  LoginView, 
  LogoutView,
  PasswordResetView,
  PasswordResetDoneView,
  PasswordResetConfirmView,
  PasswordResetCompleteView
  )
from leads.views import LandingPageView, SignUpView ,user_logout


from django.conf import settings
from django.conf.urls.static import static






urlpatterns = [
    path('admin/', admin.site.urls),
    path('',LandingPageView.as_view(),name='landing'),
    path('signup/', SignUpView.as_view(), name='sign'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', user_logout, name='logout'),


    #password reset urls 
    path('password-reset/', PasswordResetView.as_view(), name='password-reset'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('Password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

   
    path('leads/',include('leads.urls',namespace='leads')),    # urls file in the leads app
    path('agents/',include('agents.urls',namespace='agents')), # urls file in the agents app
]

if settings.DEBUG :
  urlpatterns+= static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django import forms
from leads.models import Agent
from django.contrib.auth import get_user_model #  Return the User model that is active in this project.

User = get_user_model() # we save it 

#this model is used to create the Agent.but the problem is he should be a user before 
class AgentModelForm(forms.ModelForm):
  class Meta:
    model =Agent
    fields=(
      'user', # we don't specify the organization field here 
    )

#in this updated form version. we create user account and agent account at the same time
class AgentModelFormNew(forms.ModelForm):
  class Meta:
    model = User # now the model is User and we create Agent witin the Views.py file before commit changes to the database
    fields=(   #define the fields
      'username',
      'first_name',
      'last_name',
      'email',
    )

agents/views.py
from typing import Any
import random
from django.core.mail import send_mail
from django.db.models.query import QuerySet
from django.forms import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render, reverse
from django.views import generic # generic includes the CRUD operations 
from django.contrib.auth.mixins import LoginRequiredMixin # this will check is the person loged in or not
from .mixins import OrganizerAndLoginRequiredMixin
from leads.models import Agent
from .forms import AgentModelForm ,AgentModelFormNew

class AgentListView(OrganizerAndLoginRequiredMixin,generic.ListView):
  template_name = "agents/agent-list.html"
  # queryset = Agent.objects.all() # we could use this. but let's use the following one for the query set 
  context_object_name = 'agentList'
  def get_queryset(self):
    organization = self.request.user.userprofile # we gets the userprofile of the requested user 
    return Agent.objects.filter(organization = organization)

class AgentCreateView(OrganizerAndLoginRequiredMixin,generic.CreateView):
  template_name="agents/agent-create.html"
  form_class = AgentModelFormNew
  def get_success_url(self):
    return reverse('agents:agent-list')
  
  #in the AgentModelForm we didn't add the organization field. we going to add it in here 

  def form_valid(self,form):

    # agent = form.save(commit=False)
    # agent.organization = self.request.user.userprofile
    # agent.save()
#the above ones were used when AgentModelForm is Used
#now we going to use AgentModelFormNew model so i will create the user first then the Agent as follows
      newUser = form.save(commit=False) # do not save the data intothe database yet
      newUser.is_agent = True           # make that newly created user as and Agent
      newUser.is_organizer = False 
      newUser.set_password(f"{random.randint(0,1000000)}")     # now he is not an Organizer
      newUser.save()                    # this will save the User account, now create the Agent 

      Agent.objects.create(
        user=newUser,
        organization = self.request.user.userprofile
      )
      send_mail(
        subject="You are Invited to Become as an Agent",
        message="You are Requested to become a member of DJCRM and become one of our Agent",
        from_email="admin@gmail.com",
        recipient_list = [newUser.email]
      )
      return super(AgentCreateView,self).form_valid(form)
    
class AgentDetailView(OrganizerAndLoginRequiredMixin,generic.DetailView):
  template_name="agents/agent-detail.html"
  context_object_name = "agent"
  def get_queryset(self):
    organization = self.request.user.userprofile # we gets the userprofile of the requested user 
    return Agent.objects.filter(organization = organization)


class AgentUpdateView(OrganizerAndLoginRequiredMixin,generic.UpdateView):
  template_name="agents/agent-update.html"
  form_class = AgentModelFormNew
  context_object_name ="agentUpdate"

  def get_queryset(self):
    return  Agent.objects.all()

  def get_success_url(self) :
    agent_pk = self.object.pk  # Access the updated object's primary key
    return reverse('agents:agent-detail', kwargs={'pk': agent_pk})
  
class AgentDeleteView(OrganizerAndLoginRequiredMixin,generic.DeleteView):
  template_name="agents/agent-delete.html"
  form_class=AgentModelForm
  context_object_name = 'agentDelete'

  def get_queryset(self):
    organization = self.request.user.userprofile # we gets the userprofile of the requested user 
    return Agent.objects.filter(organization = organization)
  
  def get_success_url(self):
    return reverse('agents:agent-list')
  

agents/templates/agents/agent-create.html
{% extends 'base.html' %}


{% load tailwind_filters %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block title %} Create an Agent {% endblock title %} 


{% block content %}
 

<div class="min-h-screen bg-gray-100 flex flex-col justify-center py-12 sm:px-6 lg:px-8">
  <div class="sm:mx-auto sm:w-full sm:max-w-md">
   
      
  </div>

  <div class="mt-8  sm:mx-auto sm:w-full sm:max-w-md">
    <div class="text-2xl py-4 px-6 rounded-t-lg bg-purple-800 text-white text-center font-bold uppercase">
      Create a New Agent
  </div>
      <div class="bg-white py-8 pb-20 px-4 shadow sm:rounded-lg sm:px-10">
        
          <form class="space-y-6" action="#" method="POST">
            {% csrf_token %}
            <div class="my-4">
              <label for="{{form.username.id_for_label}}" class="block text-sm font-medium text-gray-700">
                Username
              </label>
              <div class="mt-1">
                 {{form.username|add_class:" h-12 appearance-none rounded-md relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900  focus:ring-purple-500 focus:border-purple-500 focus:z-10 sm:text-sm"|attr:"placeholder:username"}}
              </div>
            </div>
            <div class="my-4">
              <label for="{{form.first_name.id_for_label}}" class="block text-sm font-medium text-gray-700">
                first_name
              </label>
              <div class="mt-1">
                 {{form.first_name|add_class:" h-12 appearance-none rounded-md relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900  focus:ring-purple-500 focus:border-purple-500 focus:z-10 sm:text-sm"|attr:"placeholder:first name"}}
              </div>
            </div>
             <div class="my-4">
              <label for="{{form.last_name.id_for_label}}" class="block text-sm font-medium text-gray-700">
                last_name
              </label>
              <div class="mt-1">
                 {{form.last_name|add_class:" h-12 appearance-none rounded-md relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900  focus:ring-purple-500 focus:border-purple-500 focus:z-10 sm:text-sm"|attr:"placeholder:last name"}}
              </div>
            </div>
            <div class="my-4">
              <label for="{{form.email.id_for_label}}" class="block text-sm font-medium text-gray-700">
                email
              </label>
              <div class="mt-1">
                 {{form.email|add_class:" h-12 appearance-none rounded-md relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900  focus:ring-purple-500 focus:border-purple-500 focus:z-10 sm:text-sm"|attr:"placeholder:email"}}
              </div>
            </div>
            <div>
              <button type="submit"
                  class="group relative w-full flex justify-center mt-10 py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-purple-600 hover:bg-purple-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500">

                  Create The Agent
              </button>
          </div>
          </form>
          <div class=" relative text-sm top-6 ">
            <a href="{% url 'agents:agent-list' %}"
            class="font-medium text-purple-700 hover:text-purple-500">
                Go back to Agents
            </a>
        </div>
      </div>
  </div>
</div>



  




<script src="https://cdn.tailwindcss.com"></script>

{% endblock content %}



  

agents/templates/agents/agent-delete.html
{% extends "base.html" %}


{% block title %}

{% endblock title %}


{% block content %}

<form action="" method="post">
  {% csrf_token %}
  <div class=" container h-56 flex flex-col items-center justify-center  bg-white
  mx-auto mt-36
  w-2/4 rounded-xl shadow-2xl shadow-black shadow 
  ">
    <span class=" text-[20px] ">Are You Sure You want to Delete The Agent ?</span>
    <input class=" ml-3 mt-3 text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-red-600 rounded" type="submit" value="Yes, Delete"/>
  </div>
  
</form>
{% endblock content %}
  

agents/templates/agents/agent-detail.html
{% extends 'base.html' %}
  
  {% block title %}
    Details of Leads
  {% endblock title %}
 
    
      
  
  {% block content %}
   
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">
          Lead Details
        </h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
          {{agent.user.username}}
        </h1>
        <div class="flex mb-4">
          <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Description</a>
          <a href=" {% url 'agents:agent-update' agent.pk %} " class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">update</a>
  
        </div>
        <p class="leading-relaxed mb-4">
          Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.
        </p>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Age</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Location</span>
          <span class="ml-auto text-gray-900">Sri Lanka</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500">Cell Phone</span>
          <span class="ml-auto text-gray-900">+94 74 0077 327</span>
        </div>
        <div class="flex">
          <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Button</button>
          <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
            <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
              <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
            </svg>
          </button>
        </div>
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>
  {% endblock content %}

agents/templates/agents/agent-list.html
{% extends 'base.html' %}
  
{% block title %} List of Agents {% endblock title %}  




{% block content %}

{% include 'navbar.html' %}
<section class="text-gray-600 body-font">
<div class="flex justify-between pt-5 px-5">
  <h1 class="mx-4 text-3xl">Agents</h1>

 

  

  
  <div>
  <label for="addLead">Create a New Agent :</label> <a class="text-blue-600" href=" {% url 'agents:agent-create' %} " id="addLead">Click Here</a><hr>
 
 </div>

</div>
<div class="container px-5 py-6 mx-auto flex flex-wrap">
  
  <table class="min-w-full divide-y divide-purple-200 overflow-x-auto">
    <thead class="bg-purple-700">
        <tr>
            <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-gray-50 uppercase tracking-wider">
               Name
            </th>
            <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-gray-50 uppercase tracking-wider">
                age
            </th>
            <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-gray-50 uppercase tracking-wider">
                Category
            </th>
            <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-gray-50 uppercase tracking-wider">
                agent
            </th>
            <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-gray-50 uppercase tracking-wider">
                Email
            </th>
            <th scope="col" class="px-6 py-3 text-left text-xs font-bold text-gray-50 uppercase tracking-wider">
                Actions
            </th>
        </tr>
    </thead>
    <tbody class="bg-white divide-y divide-gray-200">
      {% for agent in agentList %}
      <tr>
        <td class="px-6 py-4 whitespace-nowrap">
            <div class="flex items-center">
                <div class="flex-shrink-0 h-10 w-10">
                    <img class="h-10 w-10 rounded-full" src="https://i.pravatar.cc/150?img=1" alt="">
                </div>
                <div class="ml-4">
                    <div class="text-sm font-medium text-gray-900">
                        {{agent.user.first_name}} {{agent.last_name}}
                    </div>
                    
                </div>
            </div>
        </td>
        <td class="px-6 py-4 whitespace-nowrap ">
            <div class="text-sm text-gray-900 text-end ">{{agent.age}}</div>
            
        </td>
        <td class="px-6 py-4 whitespace-nowrap">
       
                
       
        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
            {{agent.agent}}
        </td>
        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
            jane.cooper@example.com
        </td>
        <td class="px-6 py-4 whitespace-nowrap  text-sm font-medium">
            <a href="{% url 'agents:agent-update' agent.pk %}" class="text-indigo-600 hover:text-indigo-900">Edit</a>
            <a href="#" class="ml-2 text-red-600 hover:text-red-900">Delete</a>
        </td>
    </tr>
      {% endfor %}
      




        <!-- More rows... -->

</section>




  
  
{% endblock content %}

agents/templates/agents/agent-update.html
{% extends "base.html" %}


{% block title %}
  Update the Lead
{% endblock title %}


{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">
          Agent Details
        </h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
          {{ agent.user.username }}
        </h1>
        <div class="flex mb-4">
          <a href="{% url 'agents:agent-detail' agentUpdate.pk %}"  class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Description</a>
          <a href="{% url 'agents:agent-update' agentUpdate.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">update</a>
         
         
        </div>
        <form action="." method="post">
          {% csrf_token %}
          {{form.as_p}}
          <button type="submit" class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">update</button>
          <a href="{% url 'agents:agent-delete' agentUpdate.pk %}" class="flex ml-auto w-24 my-4 text-red-400 font-semibold bg-white border-2 border-red-300 py-2 px-6 focus:outline-none hover:bg-red-600 rounded">Delete</a>
          </form>
        <div class="flex">
      
        </div>
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>

{% endblock content %}
  