agents/urls.py
from django.urls import path 
from .views import AgentListView,AgentCreateView,AgentDetailView,AgentUpdateView,AgentDeleteView

app_name = 'agents' # name of the app and also this is the name provided as namespace inside the main urls file in djcrm

urlpatterns = [
  path('',AgentListView.as_view(),name='agent-list'),
  path('create/',AgentCreateView.as_view(),name='agent-create'),
  path('<int:pk>/',AgentDetailView.as_view(),name='agent-detail'),
  path('<int:pk>/update/',AgentUpdateView.as_view(),name='agent-update'),
  path('<int:pk>/delete/',AgentDeleteView.as_view(),name='agent-delete'),
]

djcrm/urls.py
from os import name # for naming convention for urls
from django.contrib import admin
from django.urls import path,include

from django.contrib.auth.views import (
  LoginView, 
  LogoutView,
  PasswordResetView,
  PasswordResetDoneView,
  PasswordResetConfirmView,
  PasswordResetCompleteView
  )
from leads.views import LandingPageView, SignUpView ,user_logout


from django.conf import settings
from django.conf.urls.static import static






urlpatterns = [
    path('admin/', admin.site.urls),
    path('',LandingPageView.as_view(),name='landing'),
    path('signup/', SignUpView.as_view(), name='sign'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', user_logout, name='logout'),


    #password reset urls 
    path('password-reset/', PasswordResetView.as_view(), name='password-reset'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('Password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

   
    path('leads/',include('leads.urls',namespace='leads')),    # urls file in the leads app
    path('agents/',include('agents.urls',namespace='agents')), # urls file in the agents app
]

if settings.DEBUG :
  urlpatterns+= static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from .views import (
  LandingPageView,
  LeadListView, 
  LeadDetailView,
  LeadCreateView,
  LeadUpdateView,
  LeadDeleteView,
  AssignAgentView,
  CategoryView,
  CategoryDetailView,
  LeadCategoryUpdateView,
)

app_name = "leads"

urlpatterns = [

  path('',LeadListView.as_view(),name='lead-list'),
  path('<int:pk>/',LeadDetailView.as_view(),name='lead-detail'),
  path('create/',LeadCreateView.as_view(),name='lead-create'),
  path('<int:pk>/update/',LeadUpdateView.as_view(),name='lead-update'),
  path('<int:pk>/delete/', LeadDeleteView.as_view(), name='lead-delete'),
  path('<int:pk>/assign-agent/',AssignAgentView.as_view(),name='assign-agent'),

   path('category/', CategoryView.as_view(), name='category-view'),
   path('category/<int:pk>/',CategoryDetailView.as_view(),name='category-detail-view'),
   path('<int:pk>/category/',LeadCategoryUpdateView.as_view(),name='category-update-view'),
 
]

templates/base.html
<!-- load the static files  -->
 {% load static %} <!-- do not put qutation marks around the static name -->

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}  {% endblock title %}</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <link rel="stylesheet" href="{% static 'css/styles.css' %}"> <!--like include,block, endblock. the static is one of them -->
      
</head>
<body>
 
  {% block content %}
    
  {% endblock content %}
    
  
</body>
</html>

templates/navbar.html
{% load static %}

<header class="sticky top-0 bg-white shadow">
  <div class="container flex flex-col sm:flex-row justify-between items-center mx-auto py-4 px-8">
      <div class="flex items-center text-2xl">
          <div class="w-12 mr-3">
              <img src="{% static 'img/page-icon.svg' %}" alt="">
          </div>Client Link
      </div>
      <div class="flex mt-4 gap-x-8 text-lg sm:mt-0">
      {% if request.user.is_authenticated %}
        {% if  request.user.is_organizer %}
          <a class="nav-link border-b- border-purple-500 text-gray-500  hover:text-purple-800  " href="{% url 'agents:agent-list' %}">Agents</a>
        {% endif %} 
          <a class="nav-link text-gray-500  hover:text-purple-800  " href="{% url 'leads:lead-list' %}">Leads</a>
          
      </div>
      <div class=" md:block">
       <span class="px-3 text-purple-600 ">Logged in as : {{request.user.username}}</span>
          <a type="button" href="{% url 'logout' %}"
              class=" py-3 px-6 text-sm  bg-purple-500 hover:bg-purple-700 rounded-md text-white tracking-wider ">
              logout <img src="{% static 'img/right-arrow.svg' %}" class="w-5 inline-flex" alt="">
          </a>
      </div>
      {% else %}
      <div class=" md:block">
           <a type="button" href="{% url 'login' %}"
               class=" py-3 px-6 text-sm  bg-purple-500 hover:bg-purple-700 rounded-md text-white tracking-wider ">
               login <img src="{% static 'img/right-arrow.svg' %}" class="w-5 inline-flex" alt="">
           </a>
       </div>

      {% endif %}
  </div>
</header>